server:
  port: 8080
# 모든 경로를 인증없이 접근 가능하도록 설정
#security:
#  basic:
#    enabled: false
# OAuth2 클라이언트 ID 및 시크릿 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1397
    url: jdbc:mysql://localhost:3306/Bread_place
    username: root


