# MySQL 데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HotPlace
    username: root
    password: 1397

# Hibernate 설정
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

